version: "3"
services:
  filebeat:
    image: docker.elastic.co/beats/filebeat:7.17.2
    environment:
      - NODE_NAME=filebeat
      - "LS_JAVA_OPTS=-Xmx1g -Xms1g"
    env_file:
      - .env
    volumes:
      - ./filebeat.yml:/usr/share/filebeat/filebeat.yml
      - /var/run/docker.sock:/var/run/docker.sock
      - /var/lib/docker/containers/:/var/lib/docker/containers/:ro
    user: root
