metricbeat.modules:
- module: logstash
  metricsets:
    - node
    - node_stats
  period: 10s
  hosts: ["logstash:9600"]
  xpack.enabled: true

output:
  elasticsearch:
    hosts: ["${ES_HOST}"]
    username: "${ES_USER}"
    password: "${ES_PASSWORD}"