version: "3.9"

networks:
  openalex_net:
    external: true

services:
  logstash:
    build: .
    container_name: logstash_works
    environment:
      - XPACK_MONITORING_ENABLED=false
      - NODE_NAME=works
      - PIPELINE_ID=works
      - "LS_JAVA_OPTS=-Xmx6g -Xms6g"
    env_file:
      - .env
    restart: unless-stopped
    networks:
      - openalex_net

  # metricbeat:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile.metricbeat
  #   container_name: metricbeat_works
  #   depends_on:
  #     - logstash
  #   env_file:
  #     - .env
  #   command: ["-c", "/usr/share/metricbeat/metricbeat.yml", "-e"]
  #   restart: unless-stopped
  #   networks:
  #     - openalex_net
